server:
  port: 9000

spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    ignoredPatterns: /*-server/**
    order-srver-routes:
      #表示访问路径映射规则
      path: /order/**
      #服务名称
      serviceId: order-server
    user-srver-routes:
        path: /order/**
        serviceId: order-server
      #代表需要过来哪些请求头的参数现在是全部不过滤
  sensitive-headers:
#zuul:
#  host:
#    connect-timeout-millis: 15000 #HTTP连接超时大于Hystrix的超时时间
##    socket-timeout-millis: 60000   #socket超时
#  routes:
#      order-srver-routes:
#        #表示访问路径映射规则
#        path: /order/**
#        #服务名称
#        serviceId: order-server
#ribbon:        #设置ribbon的超时时间小于zuul的超时时间
#  ReadTimeout: 10000
#  ConnectTimeout: 10000






