eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080

spring:
  application:
    name: product-server
    #zipkin的服务地地址
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
     probability: 1